services:
    influxdb:
        image: influxdb:2.7.4-alpine
        container_name: influxdb2
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
            - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
            - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
            - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
        ports:
            - "8086:8086"
        volumes:
            - ./influxdb2-data:/var/lib/influxdb2
            - ./influxdb2-config:/etc/influxdb2

    redis:
        image: redis:7.2.3-alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./redis-data:/data
